config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :users, :posts
  resources :comments

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#delete'

  get 'welcome' => 'welcome#index'
  get 'newest' => 'posts#newest'

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments

end

app/models/session.rb
#ZM: You've created a model for something that does not exists! ohhhh noo! 
#ZM: It's okay to do this, but make sure you don't inherit from AR::Base
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    !!session[:user_id]
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @user = User.find_by(id: session[:user_id])
    @comments = Comment.all

  end

  def show

  end

  def new
    @comment = Comment.new
    @user = User.find_by(id: session[:user_id])

  end

  def create
    comment = Comment.new(comment_params)
    @post = Post.find(params[:comment][:post_id])
    #ZM: YOu are doing an extra DB Hit to make this happen. 
    # Instead use set the post_id.
    # comment.post_id = params[:comment][:post_id]
    comment.post = @post
    if comment.save
      redirect_to root_path
    else
      flash[:notice] = "Please Leave an Actual Comment"
      redirect_to new_comment_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    #ZM: What happens if you have 1,000,000 posts? 
    # With 1,000,000 comments? 
    #ZM: Start thinking about using .limit(50)
    @posts = Post.all
    @comments = Comment.all
  end


  def new
    @post = Post.new
    @user = User.find_by(id: session[:user_id])
  end

  def newest
    @posts = Post.all.order(created_at: :desc)
    @user = User.find_by(id: session[:user_id])
  end

  def create
    @user = User.find_by(id: session[:user_id])
    post = Post.new(post_params)
    post.user = @user
    if post.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments

  end

  def edit
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "INCORRECT LOGIN CREDENTIALS"
      redirect_to login_path
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #ZM: Indents!!!!!!!!!!!!!!!!!!!!!!
    def logged_in?
    !!session[:user_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_time(datetime)
    from_time = Time.now
    distance_of_time_in_words(from_time, datetime)

  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li id='small_comment_line'><%= @user.username %></li>
<li id='comment_line'><%= comment.text%></li>

app/views/comments/index.html.erb
<h1>Show All Comments</h1>
<ol id='comment-list'>
<!-- Use <%= render @comments  %> -->
  <% @comments.each do |comment| %>
  <%= render 'comment', comment: comment %>
  <% end %>
</ol>

app/views/comments/new.html.erb
<h1>make a new comment</h1>
  <div class='bad_error'>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
  </div>
<div id='create a comment'>
  <%= form_for @comment, url: comments_path, method: 'post' do |f| %>
  <%= f.hidden_field :user_id, :value => @user.id%>
  <%= f.hidden_field :post_id, :value => params[:post_id]%>

  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <div>
    <%= f.submit 'Create Comment' %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <center>
    <div id='main_body'>
    <!-- Make this nav bar stuff a partial, in views/shared/_nav.erb -->
      <header id='nav_bar'>
        <a href='http://www.ycombinator.com' id='y'>Y</a>
        <a href='<%= root_path %>' id='hacker_news'>Hacker News</a>
        <a href='<%= welcome_path %>' class='nav_link' id='first_link'>welcome</a>
        <a href='<%= newest_path %>' class='nav_link'>new</a>

        <a href='<%= comments_path %>' class='nav_link'>comments</a>



        <a href='<%= new_post_path %>' class='nav_link' id='last_link'>submit</a>
        <% if logged_in? %>
          <a href='<%= logout_path %>' class='nav_link' id='logout'> Logout</a>
          <a href='#' class='nav_link' id='user_profile'>User | </a>
          <% else %>
        <a href='<%= login_path %>' class='nav_link' id='login'>login</a>
        <% end %>
      </header>



      <%= yield %>
    </div>
  </center>

</body>
</html>

app/views/posts/_post.html.erb
<li id='top_line'><%= link_to post.title, post %></li>
<li id='small_line'># points by <%= post_time(post.created_at) %> | <%= post.comments.count %> comments </a></li>

app/views/posts/index.html.erb
<ol id='post-list'>
  <% @posts.each do |post| %>
  <%= render 'post', post: post %>
  <% end %>
</ol>

app/views/posts/new.html.erb
<h1>form for a new post</h1>
<div id='create_post'>
<!-- If your @user is a hydrated instance, and your @post is empty, you have no need to specify the url and method with a form_for -->
  <%= form_for [@user, @post], url: posts_path, method: 'post' do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div>
      <%= f.label :text %>
      <%= f.text_area :text %>
    </div>
    <div>
      <%= f.submit 'Create Post' %>
    </div>
  <% end %>
</div>

app/views/posts/newest.html.erb
<ol id='post-list'>
  <% @posts.each do |post| %>
  <%= render 'post', post: post %>
  <% end %>
</ol>

app/views/posts/show.html.erb
<h1>Show the comments for the individual post</h1>
<div id='add_comment_button'>
  <% if logged_in? %>
    <%= link_to 'Add a comment', new_post_comment_path(@post) %>
  <% end %>
</div>
<div id='post_details'>
  <%= @post.text %>
</div>
<div id='indiv_comments'>
  <% @comments.map do |comment| %>
    <ol id='comment_list'>
      <%= comment.text %>
    </ol>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Hacker News</h1>
<div id ='welcome_page'>
<p>
Hacker News is a bit different from other community sites, so we'd appreciate it if you'd take a minute to read the site guidelines.
</p>
<p>
HN is an experiment. As a rule, a community site that becomes popular will decline in quality. Our hypothesis is that this is not inevitable—that by making a conscious effort to resist decline, we can keep it from happening.
</p>
<p>
Essentially there are two rules here: don't post or upvote crap links, and don't be rude or dumb in comment threads.
</p>
<p>
A crap link is one that's only superficially interesting. Stories on HN don't have to be about hacking, because good hackers aren't only interested in hacking, but they do have to be deeply interesting.
</p>
<p>
What does "deeply interesting" mean? It means stuff that teaches you about the world. A story about a robbery, for example, would probably not be deeply interesting. But if this robbery was a sign of some bigger, underlying trend, perhaps it could be.
</p>
<p>
The worst thing to post or upvote is something that's intensely but shallowly interesting: gossip about famous people, funny or cute pictures or videos, partisan political articles, etc. If you let that sort of thing onto a news site, it will push aside the deeply interesting stuff, which tends to be quieter.
</p>
<p>
The most important principle on HN, though, is to make thoughtful comments. Thoughtful in both senses: civil and substantial.
</p>
<p>
The test for substance is a lot like it is for links. Does your comment teach us anything? There are two ways to do that: by pointing out some consideration that hadn't previously been mentioned, and by giving more information about the topic, perhaps from personal experience. Whereas comments like "LOL!" or worse still, "That's retarded!" teach us nothing.
</p>
<p>
Empty comments can be ok if they're positive. There's nothing wrong with submitting a comment saying just "Thanks." What we especially discourage are comments that are empty and negative—comments that are mere name-calling.
</p>
<p>
Which brings us to the most important principle on HN: civility. Since long before the web, the anonymity of online conversation has lured people into being much ruder than they'd be in person. So the principle here is: don't say anything you wouldn't say face to face. This doesn't mean you can't disagree. But disagree without calling names. If you're right, your argument will be more convincing without them.
</p>
</div>